routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* ---------------------------------------
/ Front controller
--------------------------------------- */
Route::get('/', 'HomeController@index')->name('home');
Route::get('/commitment', 'HomeController@commitment')->name('commitment');
Route::post('/opinion', 'OpinionController@store')->name('opinion');
Route::get('/success', 'OpinionController@success')->name('success');
Route::get('/get-subtype', 'OpinionController@get_subtype');

/* ---------------------------------------
/ Backend controller
--------------------------------------- */
Auth::routes([
    'verify' => false,
    'register' => false,
    'reset' => false,
    'password.confirm' => false,
]);

Route::resource('/opinions', 'Backend\OpinionController');
Route::post('/opinion-note-add', 'Backend\OpinionController@note_add');
Route::get('/opinion-pdf', 'Backend\PdfController@opinion_pdf');

//to clear all cache
Route::get('__clear',function(){
    try{
        \Artisan::call('cache:clear');
        \Artisan::call('view:clear');
        \Artisan::call('config:clear');
        \Artisan::call('config:cache');
        \Artisan::call('route:clear');
    }
    catch(\Exception $e){
        echo $e->getMessage();
    }
});

app/Opinion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Opinion extends Model
{
    // date accessor for date show
    function getCreatedAtAttribute($value){
        return date('d M, Y H:i A', strtotime($value)); 
    }
}

app/opinion_types.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class opinion_types extends Model
{
    // use soft delete
    use SoftDeletes;
}

app/Http/Controllers/Backend/OpinionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Note;
use App\Opinion;
use App\opinion_types;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;

class OpinionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * for show opinoin list
     */
    public function index(Request $request)
    {
        $data['request'] = $request;
        $data['title'] = 'Opinion List';
        $query = Opinion::leftJoin('opinion_types','opinions.type','=','opinion_types.id');
                        // ->leftJoin('opinion_type_subs','opinions.sub_type','=','opinion_type_subs.id');
        if($request->name){
            $query->where('opinions.name', 'like', '%' . $request->name . '%');
        }
        if($request->phone){
            $query->where('opinions.phone', 'like', '%' . $request->phone . '%');
        }
        if($request->email){
            $query->where('opinions.email', 'like', '%' . $request->email . '%');
        }
        if($request->age){
            $query->where('opinions.age', 'like', '%' . $request->age . '%');
        }
        if($request->profession){
            $query->where('opinions.profession', 'like', '%' . $request->profession . '%');
        }
        if($request->union){
            $query->where('opinions.ward', 'like', '%' . $request->union . '%');
        }
        if($request->address){
            $query->where('opinions.address', 'like', '%' . $request->address . '%');
        }
        if($request->type){
            $query->where('opinions.type',$request->type);
        }
        // if($request->sub_type){
        //     $query->where('opinions.sub_type',$request->sub_type);
        // }
        if($request->year){
            $query->where('opinions.year',$request->year);
        }
        $data['lists'] = $query->select('opinions.*','opinion_types.name as opinion_type_name')->orderBy('id','desc')->paginate(20); //,'opinion_type_subs.name as opinion_sub_type_name'
        $data['types'] = opinion_types::orderBy('sort','asc')->get();
        return view('backend.opinion.list', $data);
    }

    /*
     */
    public function create(Request $request)
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
    /**
     * add note
     */
    public function note_add(Request $request)
    {
        try {
            $data = new Note();
            $data->opinion_id = $request->id;
            $data->note = $request->note;
            $data->save();
            Toastr::success('যুক্ত হয়েছে', 'সফল');
            return redirect()->back();
        } catch (ModelNotFoundException $e) {
            Toastr::error($e->getMessage(), 'Warning');
            return redirect()->back();
        }
    }

}

app/Http/Controllers/Backend/PdfController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Opinion;
use Illuminate\Http\Request;
use PDF;

class PdfController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * opinion PDF generate
     */
    public function opinion_pdf(Request $request)
    {
        // dd($request);
        $data['lists'] = Opinion::leftJoin('opinion_types','opinions.type','=','opinion_types.id')
                                    ->where('opinions.name', 'like', '%' . $request->name . '%')
                                    ->where('opinions.phone', 'like', '%' . $request->phone . '%')
                                    ->where('opinions.email', 'like', '%' . $request->email . '%')
                                    ->where('opinions.age', 'like', '%' . $request->age . '%')
                                    ->where('opinions.profession', 'like', '%' . $request->profession . '%')
                                    ->where('opinions.ward', 'like', '%' . $request->ward . '%')
                                    ->where('opinions.address', 'like', '%' . $request->address . '%')
                                    ->where('opinion_types.name', 'like', '%' . $request->type . '%')
                                    ->select('opinions.*','opinion_types.name as opinion_type_name')
                                    ->paginate(20);
        $pdf = PDF::loadView('backend.opinion.opinion_pdf', $data);
        // $pdf->setPaper('A4', 'landscape');
        // $pdf->SetProtection(['copy', 'print'], '', 'pass');
        return $pdf->stream('pdfview.pdf');

        // $pdf = PDF::loadView('pdf.document', $data);
        // $pdf->SetProtection(['copy', 'print'], '', 'pass');
        // return $pdf->stream('document.pdf');
    }
}

app/Http/Controllers/OpinionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OpinionRequest;
use Illuminate\Http\Request;
use App\Opinion;
use App\opinion_types;
use App\OpinionTypeSubs;
use Session;
// use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class OpinionController extends Controller
{
    /**
     * for save public opinoin
     */
    public function store(OpinionRequest $request){
        // dd($request);
        try {
            $pinion = new Opinion();
            $pinion->name = $request->name;
            $pinion->phone = $request->phone;
            $pinion->email = $request->email;
            $pinion->age = $request->age;
            $pinion->gender = $request->gender;
            $pinion->profession = $request->profession;
            $pinion->ward = $request->union;
            $pinion->address = $request->address;
            $pinion->type = $request->type;
            // $pinion->sub_type = $request->sub_type;
            $pinion->opinion = $request->opinion;
            $pinion->year = $request->year;
            $pinion->save();
            // show success msg
            // $data['name']=$pinion->name;
            // return redirect()->back();
            // Toastr::success('Messages in here', 'Title');
            Session::flash('name', $pinion->name);
            return redirect('/success');
        } catch (ModelNotFoundException $e) {
            // Toastr::error($e->getMessage(), 'Warning');
            return redirect()->back();
        }
    }
    /**
     * for show success page
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function success()
    {
        if(!Session::has('name')){
            return redirect('/');
        }
        $data['title'] = 'শেখ ফজলে নূর তাপস';
        $data['is_success'] = true;
        return view('success', $data);
    }
    /**
     * get sub type of main type
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function get_subtype(Request $request)
    {
        $result = OpinionTypeSubs::where('opinion_type_id', $request->type)->orderBy('sort','asc')->get();
        return response()->json($result, 200);
    }
}

resources/views/backend/opinion/opinion_pdf.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>User list - PDF</title>
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <style>
        body{
            font-family:bangla;
        }
        .table-pdf {
            width: 100%;
        }
        .table-pdf thead tr th{
            text-align: center;
            background: #eee;
            font-weight: bold;
            padding: 5px 10px;
            font-size: 17px;
        }
        .table-pdf thead tr th, .table-pdf tbody tr td {
            padding: 4px;
            font-size: 12px !important;
        }
        table.table tbody tr td{
            background: transparent !important;
            vertical-align: top;
        }
        table.table-header{
            width: 100%;
        }
        table.table-header tr td.last-child{
            text-align: right !important;
        }
        .content-header h2, .content-header h3{
            margin: 0px;
            padding: 0px;
        }
        .bg-wm{
            background: url("assets/back/dist/images/gov-logo-wm.png");
            background-size: contain;
            background-position: center;
            background-repeat: no-repeat;
        }
        </style>
    </head>
    <body>
        <style>
            body {
                font-family: 'bangla', sans-serif;
            }
        </style>
        <div class="container">
            <div class="row">
                <div class="box box-success profile-sec bn">
                    <h3 class="text-center m-0 p-0">প্রত্যাশিত ঢাকার (দক্ষিণ) নবসূচনায় নাগরিক মতামত</h3>
                    <p class="text-center m-0 p-0">রিপোর্টিং টাইম: {{ date('d M, Y h:i A')  }}</p>
                    <div class="row">
                        <div class="col-xs-12">
                            <!-- header -->
                            <div class="row col-md-12">
                                <table id="" class="table table-responsive table-bordered table-report bg-logo table-pdf">
                                    <thead>
                                        <tr>
                                            <th>নং</th>
                                            <th>নাম</th>
                                            <th>মোবাইল</th>
                                            <th>বয়স</th>
                                            <th>লিঙ্গ</th>
                                            <th>পেশা</th>
                                            <th>ওয়ার্ড</th>
                                            <th>ঠিকানা</th>
                                            <th>মতামতের ধরণ</th>
                                            <th>তারিখ ও সময়</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($lists as $key => $list)
                                        <tr>
                                            <td>{{ ++$key }}</td>
                                            <td>{{ $list->name }}</td>
                                            <td>{{ $list->phone }}</td>
                                            <td>{{ $list->age }}</td>
                                            <td>{{ $list->gender }}</td>
                                            <td>{{ $list->profession }}</td>
                                            <td>{{ $list->ward }}</td>
                                            <td>{{ $list->address }}</td>
                                            <td>{{ $list->opinion_type_name }}</td>
                                            <td>{{ $list->created_at }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>